---
- hosts: linux_lxc 
  tasks:
  - name: Upgrade all installed packages for Debian and Ubuntu
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    environment:
      DEBIAN_FRONTEND: noninteractive
      APT_LISTCHANGES_FRONTEND: none
    async: 600      # max 10 Minuten erlauben
    poll: 5         # alle 5 Sekunden prüfen 
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

