---
- hosts: linux_lxc
  gather_facts: true
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
  tasks:
    - name: Upgrade aller installierten Pakete für Debian und Ubuntu
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      async: 600
      poll: 5
      when: ansible_distribution in ['Ubuntu', 'Debian']
      register: upgrade_result
      ignore_errors: true

    - name: Erfolg oder Fehler als Host-Fact speichern
      set_fact:
        upgrade_status: "{{ '✅ Erfolgreich' if upgrade_result is succeeded else '❌ Fehler' }}"

- hosts: localhost
  gather_facts: false
  vars:
    discord_webhook_url_from_inventory: "{{ hostvars[groups['linux_lxc'][0]].discord_webhook_url_from_inventory }}"
  tasks:
    - name: Alle Upgrade-Ergebnisse sammeln
      set_fact:
        upgrade_summary: |
          {% for item in groups['linux_lxc'] %}
          - {{ item }}: {{ hostvars[item]['upgrade_status'] }}
          {% endfor %}
          _Zeit: {{ ansible_date_time.date }} {{ ansible_date_time.time }}_

    - name: Nachricht an Discord senden
      uri:
        url: "{{ discord_webhook_url_from_inventory }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          content: "{{ upgrade_summary }}"
        body_format: json
        status_code: 204
