---
- hosts: linux_lxc
  gather_facts: true
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
  tasks:
    - name: Upgrade aller installierten Pakete für Debian und Ubuntu
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      async: 600
      poll: 5
      when: ansible_distribution in ['Ubuntu', 'Debian']
      register: upgrade_result
      ignore_errors: true

    - name: Erfolg oder Fehler setzen
      set_fact:
        upgrade_status: "{{ '✅ Erfolgreich' if upgrade_result is succeeded else '❌ Fehler' }}"

    - name: Status an Controller-Host übergeben
      add_host:
        name: localhost
        groups: result_collector
        host_status: "{{ inventory_hostname }}: {{ upgrade_status }}"

- hosts: result_collector
  gather_facts: false
  tasks:
    - name: Alle Upgrade-Ergebnisse sammeln
      set_fact:
        upgrade_summary: "{{ upgrade_summary | default([]) + [hostvars[item]['host_status']] }}"
      loop: "{{ groups['linux_lxc'] }}"

    - name: Upgrade Summary erzeugen
      set_fact:
        discord_message: |
          **Upgrade-Report**
          {% for result in upgrade_summary %}
          - {{ result }}
          {% endfor %}
          _Zeit: {{ ansible_date_time.date }} {{ ansible_date_time.time }}_

    - name: Nachricht an Discord senden
      uri:
        url: "{{ hostvars[groups['linux_lxc'][0]].discord_webhook_url_from_inventory }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          content: "{{ discord_message }}"
        body_format: json
        status_code: 204
