---
- hosts: linux_lxc
  gather_facts: true
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
  tasks:
    - name: Upgrade aller installierten Pakete für Debian und Ubuntu
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      async: 600
      poll: 5
      when: ansible_distribution in ['Ubuntu', 'Debian']
      register: upgrade_result
      ignore_errors: true

    - name: Erfolg oder Fehler als Host-Fact speichern
      set_fact:
        upgrade_status: "{{ '✅ Erfolgreich' if upgrade_result is succeeded else '❌ Fehler' }}"

    - name: Timestamp setzen
      set_fact:
        upgrade_timestamp: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- hosts: localhost
  gather_facts: false
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
  tasks:
    - name: Alle Upgrade-Ergebnisse sammeln
      set_fact:
        upgrade_summary: |
          {% for item in groups['linux_lxc'] %}
          - {{ item }}: {{ hostvars[item]['upgrade_status'] }}
          {% endfor %}

    - name: Nachricht an Discord senden
      uri:
        url: "{{ discord_webhook_url_from_inventory }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          embeds:
            - title: "Upgrade-Report"
              description: "{{ upgrade_summary }}"
              color: 5814783  # ein schönes Blau-Grün für OK
              footer:
                text: "Stand: {{ hostvars[groups['linux_lxc'][0]]['upgrade_timestamp'] }}"
        body_format: json
        status_code: 204
