---
- hosts: linux_lxc
  gather_facts: true
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
  tasks:
    - name: Upgrade aller installierten Pakete für Debian und Ubuntu
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      async: 600
      poll: 5
      when: ansible_distribution in ['Ubuntu', 'Debian']
      register: upgrade_result
      ignore_errors: true

    - name: Erfolg oder Fehler als Host-Fact speichern
      set_fact:
        upgrade_status: "{{ 'success' if upgrade_result is succeeded else 'failed' }}"

    - name: Timestamp setzen
      set_fact:
        upgrade_timestamp: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- hosts: localhost
  gather_facts: false
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
  tasks:
    - name: Alle Upgrade-Ergebnisse sammeln
      set_fact:
        upgrade_summary: |
          {% set success_count = 0 %}
          {% set fail_count = 0 %}
          {% for item in groups['linux_lxc'] %}
            {% if hostvars[item]['upgrade_status'] == 'success' %}
              {% set success_count = success_count + 1 %}
            {% else %}
              {% set fail_count = fail_count + 1 %}
            {% endif %}
          {% endfor %}
          {% set _ = namespace(success=success_count, fail=fail_count) %}
          {% for item in groups['linux_lxc'] %}
          - {{ item }}: {{ '✅ Erfolgreich' if hostvars[item]['upgrade_status'] == 'success' else '❌ Fehler' }}
          {% endfor %}
        success_count: "{{ success_count }}"
        fail_count: "{{ fail_count }}"
        upgrade_timestamp: "{{ hostvars[groups['linux_lxc'][0]]['upgrade_timestamp'] }}"

    - name: Farbe für Discord bestimmen
      set_fact:
        discord_color: >-
          {% if fail_count == 0 %}
            65280            # grün
          {% elif success_count == 0 %}
            16711680         # rot
          {% else %}
            16776960         # gelb
          {% endif %}

    - name: Nachricht an Discord senden
      uri:
        url: "{{ discord_webhook_url_from_inventory }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body:
          embeds:
            - title: "Upgrade-Report"
              description: "{{ upgrade_summary }}"
              color: "{{ discord_color | int }}"
              footer:
                text: "Stand: {{ upgrade_timestamp }}"
        body_format: json
        status_code: 204
