---
- hosts: linux_lxc
  vars:
    discord_webhook_url_from_inventory: "{{ discordwebhook }}"
    discord_message: ""
  tasks:
    - name: Upgrade all installed packages für Debian und Ubuntu
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      async: 600
      poll: 5
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
      register: upgrade_result
      ignore_errors: true  # Wichtig: Play läuft weiter, auch bei Fehler

    - name: Setze Erfolgsmeldung
      set_fact:
        discord_message: |
          ✅ Upgrade erfolgreich auf {{ inventory_hostname }}
          Zeit: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
      when: upgrade_result is succeeded

    - name: Setze Fehlermeldung
      set_fact:
        discord_message: |
          ⚠️ Upgrade FEHLGESCHLAGEN auf {{ inventory_hostname }}
          Zeit: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
      when: upgrade_result is failed

    - name: Sende Status an Discord
      uri:
        url: "{{ discord_webhook_url_from_inventory }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "content": "{{ discord_message }}"
          }
        body_format: json
        status_code: 204
